[package]
name = "voxxel_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.38"
gl = "0.14.0"
nalgebra-glm = "0.20.0"
image = "0.25.9"
fontdue = "0.9.3"

[lib]
name = "voxxel_engine"
path = "src/lib.rs"